version: "1.0"
services:
  django:
   # image: django:latest
    build: percussatsight/.
    container_name: django-backend
    ports: 
      - "80:80"
    volumes: 
      - ./percussatsight/:/usr/src/app/ #connect percussatsight to the container
  database:
    image: mysql:latest
    container_name: database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=p@sSw0Rd
      - MYSQL_DATABASE=users
      - MYSQL_USER=django
      - MYSQL_PASSWORD=p@sSw0Rd
#    volumes:
#      - ./database:/etc/mysq/
