version: "3.0"
services:
  django:
    # image: django:latest
    build: percussatsight/.
    container_name: django-backend
    ports:
      - "8080:8080"
    expose:
      - "3306"
    volumes:
      - ./percussatsight/:/usr/src/app/ #connect percussatsight to the container
#    networks:
#      default:
#        ipv4_address: 172.24.0.1
    depends_on:
      - database
  database:
    image: mysql:latest
    container_name: database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=p@sSw0Rd
      - MYSQL_DATABASE=percussatsight
      - MYSQL_USER=django
      - MYSQL_PASSWORD=p@sSw0Rd
    volumes:
      - ./database:/etc/mysq/
#    networks:
#      default:
#        ipv4_address: 172.24.0.2
  vue-frontend:
    build: vue/.
    container_name: vue-frontend
    ports:
      - "80:80"
#    networks:
#      default:
#        ipv4_address: 172.24.0.3
#networks:
#  default:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.24.0.0/24
#          gateway: 172.24.0.254
