version: "3.0"
services:
  django:
   # image: django:latest
    build: percussatsight/.
    container_name: django-backend
    ports: 
      - "8080:8080"
    volumes: 
      - ./percussatsight/:/usr/src/app/ #connect percussatsight to the container
  database:
    image: mysql:latest
    container_name: database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=p@sSw0Rd
      - MYSQL_DATABASE=users
      - MYSQL_USER=root
      - MYSQL_PASSWORD=p@sSw0Rd
    volumes:
      - ./database:/etc/mysq/
  vue-frontend:
    build: vue/.
    container_name: vue-frontend
    ports: 
      - "80:80"
